/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoinsSlugRouteImport } from './routes/coins.$slug'
import { Route as FormatsSlugRouteImport } from './routes/formats.$slug'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsSplatRouteImport } from './routes/markets.$'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as NewsCategoryIndexRouteImport } from './routes/news.$category.index'
import { Route as NewsCategorySubcategoryIndexRouteImport } from './routes/news.$category.$subcategory.index'
import { Route as NewsCategorySubcategorySlugRouteImport } from './routes/news.$category.$subcategory.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsSlugRoute = CoinsSlugRouteImport.update({
  id: '/coins/$slug',
  path: '/coins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatsSlugRoute = FormatsSlugRouteImport.update({
  id: '/formats/$slug',
  path: '/formats/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsSplatRoute = MarketsSplatRouteImport.update({
  id: '/markets/$',
  path: '/markets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsCategoryIndexRoute = NewsCategoryIndexRouteImport.update({
  id: '/news/$category/',
  path: '/news/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsCategorySubcategoryIndexRoute =
  NewsCategorySubcategoryIndexRouteImport.update({
    id: '/news/$category/$subcategory/',
    path: '/news/$category/$subcategory/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsCategorySubcategorySlugRoute =
  NewsCategorySubcategorySlugRouteImport.update({
    id: '/news/$category/$subcategory/$slug',
    path: '/news/$category/$subcategory/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coins/$slug': typeof CoinsSlugRoute
  '/formats/$slug': typeof FormatsSlugRoute
  '/markets/$': typeof MarketsSplatRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/markets/': typeof MarketsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/news/$category/': typeof NewsCategoryIndexRoute
  '/news/$category/$subcategory/$slug': typeof NewsCategorySubcategorySlugRoute
  '/news/$category/$subcategory/': typeof NewsCategorySubcategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coins/$slug': typeof CoinsSlugRoute
  '/formats/$slug': typeof FormatsSlugRoute
  '/markets/$': typeof MarketsSplatRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/markets': typeof MarketsIndexRoute
  '/news': typeof NewsIndexRoute
  '/news/$category': typeof NewsCategoryIndexRoute
  '/news/$category/$subcategory/$slug': typeof NewsCategorySubcategorySlugRoute
  '/news/$category/$subcategory': typeof NewsCategorySubcategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coins/$slug': typeof CoinsSlugRoute
  '/formats/$slug': typeof FormatsSlugRoute
  '/markets/$': typeof MarketsSplatRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/markets/': typeof MarketsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/news/$category/': typeof NewsCategoryIndexRoute
  '/news/$category/$subcategory/$slug': typeof NewsCategorySubcategorySlugRoute
  '/news/$category/$subcategory/': typeof NewsCategorySubcategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coins/$slug'
    | '/formats/$slug'
    | '/markets/$'
    | '/topics/$slug'
    | '/markets/'
    | '/news/'
    | '/news/$category/'
    | '/news/$category/$subcategory/$slug'
    | '/news/$category/$subcategory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coins/$slug'
    | '/formats/$slug'
    | '/markets/$'
    | '/topics/$slug'
    | '/markets'
    | '/news'
    | '/news/$category'
    | '/news/$category/$subcategory/$slug'
    | '/news/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/coins/$slug'
    | '/formats/$slug'
    | '/markets/$'
    | '/topics/$slug'
    | '/markets/'
    | '/news/'
    | '/news/$category/'
    | '/news/$category/$subcategory/$slug'
    | '/news/$category/$subcategory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoinsSlugRoute: typeof CoinsSlugRoute
  FormatsSlugRoute: typeof FormatsSlugRoute
  MarketsSplatRoute: typeof MarketsSplatRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  NewsCategoryIndexRoute: typeof NewsCategoryIndexRoute
  NewsCategorySubcategorySlugRoute: typeof NewsCategorySubcategorySlugRoute
  NewsCategorySubcategoryIndexRoute: typeof NewsCategorySubcategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins/$slug': {
      id: '/coins/$slug'
      path: '/coins/$slug'
      fullPath: '/coins/$slug'
      preLoaderRoute: typeof CoinsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formats/$slug': {
      id: '/formats/$slug'
      path: '/formats/$slug'
      fullPath: '/formats/$slug'
      preLoaderRoute: typeof FormatsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$': {
      id: '/markets/$'
      path: '/markets/$'
      fullPath: '/markets/$'
      preLoaderRoute: typeof MarketsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$category/': {
      id: '/news/$category/'
      path: '/news/$category'
      fullPath: '/news/$category/'
      preLoaderRoute: typeof NewsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$category/$subcategory/': {
      id: '/news/$category/$subcategory/'
      path: '/news/$category/$subcategory'
      fullPath: '/news/$category/$subcategory/'
      preLoaderRoute: typeof NewsCategorySubcategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$category/$subcategory/$slug': {
      id: '/news/$category/$subcategory/$slug'
      path: '/news/$category/$subcategory/$slug'
      fullPath: '/news/$category/$subcategory/$slug'
      preLoaderRoute: typeof NewsCategorySubcategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoinsSlugRoute: CoinsSlugRoute,
  FormatsSlugRoute: FormatsSlugRoute,
  MarketsSplatRoute: MarketsSplatRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  MarketsIndexRoute: MarketsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  NewsCategoryIndexRoute: NewsCategoryIndexRoute,
  NewsCategorySubcategorySlugRoute: NewsCategorySubcategorySlugRoute,
  NewsCategorySubcategoryIndexRoute: NewsCategorySubcategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
